In [ ]:
# Program 1: Calculate total weekly energy from a list
daily_kwh = [400,500,700,400,600,300,200,500,600]
total_energy = sum(daily_kwh)
print("Total Energy Used:", total_energy , "kwh")

Total Energy Used: 4200 kwh

In [ ]:
# Program 2: Store building Usuage data
building_usuage = {
    "CSE" : 700,
    "HOSTEL" : 500
}
print("Hostel Usuage:",building_usuage["HOSTEL"],"Kwh")

Hostel Usuage: 500 Kwh

In [1]:
# Program 3: A function to calculate electricity cost
def calculate_bill(kwh,rate_per_unit):
  return kwh * rate_per_unit
todays_bill = calculate_bill(600,8)
print("Today's estimated bill is Rs.", todays_bill)

Today's estimated bill is Rs. 4800

In [3]:
# Program 4: Read a file line-by line
with open("campus_energy.csv", "r") as file:
   for line in file.readlines():
      print(line.strip())

Date,Building,kwh_used,Peak_hours_ used
15-10-2026,CSE,400,120
16-10-2026,HOSTAL,500,250
17-10-2026,CSE,700,110
18-10-2026,ECE,400,325
19-10-2026,CIVIL,600,210
20-10-2026,MECH,300,111
21-10-2026,AIML,200,320
22-10-2026,AIDS,500,250
23-10-2026,BBA,600,117

In [6]:
# import the pandas library
import pandas as pd

# load the dataset you created
df = pd.read_csv("campus_energy.csv")

# display the first few rows of the data
print("Here is the raw data:")
display(df.head())

# Group the data to see total usage per building
building_totals = df.groupby("Building")["kwh_used"].sum()

print("\nTotal usage per building:")
print(building_totals)

# Generate a statistical summary (average, min, max) of the numeric columns
print("\nStatistical Summary:")
display(df.describe())

Here is the raw data:

         Date Building  kwh_used  Peak_hours_ used
0  15-10-2026      CSE       400               120
1  16-10-2026   HOSTAL       500               250
2  17-10-2026      CSE       700               110
3  18-10-2026      ECE       400               325
4  19-10-2026    CIVIL       600               210

Total usage per building:
Building
AIDS       500
AIML       200
BBA        600
CIVIL      600
CSE       1100
ECE        400
HOSTAL     500
MECH       300
Name: kwh_used, dtype: int64

Statistical Summary:

         kwh_used  Peak_hours_ used
count    9.000000          9.000000
mean   466.666667        201.444444
std    158.113883         89.733092
min    200.000000        110.000000
25%    400.000000        117.000000
50%    500.000000        210.000000
75%    600.000000        250.000000
max    700.000000        325.000000

In [7]:
# create the README.md file and write a message inside it

with open("README.md", "w") as file:
  file.write("# Smart Campus Energy project\n")
  file.write("This repository contains My week 1 hands-on Python and pandas assignments:\n")
  file.write("created by: [Dileep poneti]")

  print("README.md has been successfully created")

README.md has been successfully created